name: üßÆ GitHub Metrics

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: metrics.svg
          user: 92Infinitus92

          template: classic

          base: header, activity, community, repositories, metadata
          base_indepth: yes

          config_timezone: Europe/Sofia
          config_display: large
          config_animations: yes

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_followup: yes

          plugin_topics: no

          # ‚≠ê Language analytics
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 500
          plugin_languages_sections: most-used, recently-used

          # ‚≠ê Repo analytics
          plugin_repositories: yes
          repositories_forks: no

          # ‚≠ê Punchcard
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # ‚≠ê Coding habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
